global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000']
        labels:
          application: 'api-gateway'
  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'product service'
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'order service'
  - job_name: 'inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'inventory service'
  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'notification service'